//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:46:43 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/C/fpp/ND280/00010000_00010999/anal/oa_nd_cos_00010252-0000_u6mzlh635zkw_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__ToaAnalysisUtils_h
#define ND__ToaAnalysisUtils_h
namespace ND {
class ToaAnalysisUtils;
} // end of namespace.

#include "TObject.h"

namespace ND {
class ToaAnalysisUtils : public TObject {

public:
// Nested classes forward declaration.
enum EParticleCategory { kDefault_EParticleCategory };
enum ESubdetector { kDefault_ESubdetector };

public:
// Nested classes declaration.

public:
// Data Members.

   ToaAnalysisUtils();
   ToaAnalysisUtils(const ToaAnalysisUtils & );
   virtual ~ToaAnalysisUtils();

   ClassDef(ToaAnalysisUtils,2); // Generated by MakeProject.
};
} // namespace
#endif
