//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:46:44 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/C/fpp/ND280/00010000_00010999/anal/oa_nd_cos_00010252-0000_u6mzlh635zkw_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGRooTrackerVtxModule_h
#define ND__TGRooTrackerVtxModule_h
namespace ND {
class TGRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TGRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TGRooTrackerVtxModule();
   TGRooTrackerVtxModule(const TGRooTrackerVtxModule & );
   virtual ~TGRooTrackerVtxModule();

   ClassDef(TGRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
