//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:44:17 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/B/rdp/ND280/00009000_00009999/anal/oa_nd_cos_00009000-0001_l5imkgmhu4io_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisHeaderModuleBase_h
#define ND__TAnalysisHeaderModuleBase_h
namespace ND {
class TAnalysisHeaderModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisHeaderModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisHeaderModuleBase();
   TAnalysisHeaderModuleBase(const TAnalysisHeaderModuleBase & );
   virtual ~TAnalysisHeaderModuleBase();

   ClassDef(TAnalysisHeaderModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
