//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:44:17 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/B/rdp/ND280/00009000_00009999/anal/oa_nd_cos_00009000-0001_l5imkgmhu4io_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TExample2010aAnalysis1Module_h
#define ND__TExample2010aAnalysis1Module_h
namespace ND {
class TExample2010aAnalysis1Module;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TExample2010aAnalysis1Module : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Double_t    fTimeOffset;    //

   TExample2010aAnalysis1Module();
   TExample2010aAnalysis1Module(const TExample2010aAnalysis1Module & );
   virtual ~TExample2010aAnalysis1Module();

   ClassDef(TExample2010aAnalysis1Module,2); // Generated by MakeProject.
};
} // namespace
#endif
