//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:48:41 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/C/fpp/ND280/00010000_00010999/anal/oa_nd_cos_00010252-0000_u6mzlh635zkw_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisModuleBase_h
#define ND__TAnalysisModuleBase_h
namespace ND {
class TAnalysisModuleBase;
} // end of namespace.

#include "TNamed.h"
#include "TTree.h"
#include "Riostream.h"
#include <string>

namespace ND {
class TAnalysisModuleBase : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   Bool_t      fIsEnabled;    //
   Bool_t      fIsUsedForPreselection;    //
   TTree*      fOutputTree;               //
   Int_t       fBufferSize;               //Buffer Size for TBranch.
   Int_t       fSplitLevel;               ///< Split Level for TBranch.
   string      fDescription;              ///< A longish descrition of the analysis
   string      fCVSTagName;               ///< Defined if an official tagged version
   string      fCVSID;                    ///< Defined if an official tagged version
   Int_t       fRunID;                    //
   Int_t       fSubrunID;                 //
   Int_t       fEventID;                  //
   Int_t       fPreselected;              //
   string      fInputDirectory;           ///< An input directory where analysis modules can search for extra files.

   TAnalysisModuleBase();
   TAnalysisModuleBase(const TAnalysisModuleBase & );
   virtual ~TAnalysisModuleBase();

   ClassDef(TAnalysisModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
