//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:48:42 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/C/fpp/ND280/00010000_00010999/anal/oa_nd_cos_00010252-0000_u6mzlh635zkw_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TNRooTrackerVtxModule_h
#define ND__TNRooTrackerVtxModule_h
namespace ND {
class TNRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TNRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TNRooTrackerVtxModule();
   TNRooTrackerVtxModule(const TNRooTrackerVtxModule & );
   virtual ~TNRooTrackerVtxModule();

   ClassDef(TNRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
