//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:48:41 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/C/fpp/ND280/00010000_00010999/anal/oa_nd_cos_00010252-0000_u6mzlh635zkw_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TBasicDataQualityModule_h
#define ND__TBasicDataQualityModule_h
namespace ND {
class TBasicDataQualityModule;
} // end of namespace.

#include "ND__TAnalysisHeaderModuleBase.h"

namespace ND {
class TBasicDataQualityModule : public ND::TAnalysisHeaderModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TBasicDataQualityModule();
   TBasicDataQualityModule(const TBasicDataQualityModule & );
   virtual ~TBasicDataQualityModule();

   ClassDef(TBasicDataQualityModule,2); // Generated by MakeProject.
};
} // namespace
#endif
