//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:42:42 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/B/rdp/ND280/00009000_00009999/anal/oa_nd_cos_00009000-0001_l5imkgmhu4io_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALPi0ReconModule_h
#define ND__TTrackerECALPi0ReconModule_h
namespace ND {
class TTrackerECALPi0ReconModule;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TTrackerECALPi0ReconModule : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TTrackerECALPi0ReconModule();
   TTrackerECALPi0ReconModule(const TTrackerECALPi0ReconModule & );
   virtual ~TTrackerECALPi0ReconModule();

   ClassDef(TTrackerECALPi0ReconModule,2); // Generated by MakeProject.
};
} // namespace
#endif
