//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 27 22:42:41 2015 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/epp2/t2k/data/nd280/production006/B/rdp/ND280/00009000_00009999/anal/oa_nd_cos_00009000-0001_l5imkgmhu4io_anal_000_v11r31-wg-bugaboo-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__RooTrackerVtxBase_h
#define ND__RooTrackerVtxBase_h
namespace ND {
class RooTrackerVtxBase;
} // end of namespace.

#include "TObject.h"

namespace ND {
class RooTrackerVtxBase : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   RooTrackerVtxBase();
   RooTrackerVtxBase(const RooTrackerVtxBase & );
   virtual ~RooTrackerVtxBase();

   ClassDef(RooTrackerVtxBase,2); // Generated by MakeProject.
};
} // namespace
#endif
